(()=>{"use strict";var __webpack_modules__={"./src/js/app.js":
/*!***********************!*\
  !*** ./src/js/app.js ***!
  \***********************/(__unused_webpack_module,__webpack_exports__,__webpack_require__)=>{eval('__webpack_require__.r(__webpack_exports__);\n/* harmony export */ __webpack_require__.d(__webpack_exports__, {\n/* harmony export */   "offerAccordions": () => (/* binding */ offerAccordions)\n/* harmony export */ });\nfunction _createForOfIteratorHelper(o, allowArrayLike) { var it = typeof Symbol !== "undefined" && o[Symbol.iterator] || o["@@iterator"]; if (!it) { if (Array.isArray(o) || (it = _unsupportedIterableToArray(o)) || allowArrayLike && o && typeof o.length === "number") { if (it) o = it; var i = 0; var F = function F() {}; return { s: F, n: function n() { if (i >= o.length) return { done: true }; return { done: false, value: o[i++] }; }, e: function e(_e) { throw _e; }, f: F }; } throw new TypeError("Invalid attempt to iterate non-iterable instance.\\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method."); } var normalCompletion = true, didErr = false, err; return { s: function s() { it = it.call(o); }, n: function n() { var step = it.next(); normalCompletion = step.done; return step; }, e: function e(_e2) { didErr = true; err = _e2; }, f: function f() { try { if (!normalCompletion && it["return"] != null) it["return"](); } finally { if (didErr) throw err; } } }; }\nfunction _unsupportedIterableToArray(o, minLen) { if (!o) return; if (typeof o === "string") return _arrayLikeToArray(o, minLen); var n = Object.prototype.toString.call(o).slice(8, -1); if (n === "Object" && o.constructor) n = o.constructor.name; if (n === "Map" || n === "Set") return Array.from(o); if (n === "Arguments" || /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n)) return _arrayLikeToArray(o, minLen); }\nfunction _arrayLikeToArray(arr, len) { if (len == null || len > arr.length) len = arr.length; for (var i = 0, arr2 = new Array(len); i < len; i++) arr2[i] = arr[i]; return arr2; }\nvar offerAccordions = function offerAccordions() {\n  var acPanels = document.querySelectorAll(\'.accordion__panel\');\n  var openPanels = document.querySelectorAll(\'.panel__open\');\n  var _iterator = _createForOfIteratorHelper(acPanels),\n    _step;\n  try {\n    var _loop = function _loop() {\n      var acPanel = _step.value;\n      acPanel.addEventListener(\'click\', function () {\n        acPanel.classList.toggle(\'active\');\n        openPanels.forEach(function (elem) {\n          elem.classList.toggle(\'active\');\n        });\n      });\n    };\n    for (_iterator.s(); !(_step = _iterator.n()).done;) {\n      _loop();\n    }\n  } catch (err) {\n    _iterator.e(err);\n  } finally {\n    _iterator.f();\n  }\n  ;\n};\n\n//# sourceURL=webpack://start/./src/js/app.js?')},"./src/js/cottage-slider.js":
/*!**********************************!*\
  !*** ./src/js/cottage-slider.js ***!
  \**********************************/(__unused_webpack_module,__webpack_exports__,__webpack_require__)=>{eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export */ __webpack_require__.d(__webpack_exports__, {\n/* harmony export */   \"gallarySlider\": () => (/* binding */ gallarySlider)\n/* harmony export */ });\nvar gallarySlider = function gallarySlider() {\n  var prevBtn = document.querySelector('.slider__btn-prev');\n  var nextBtn = document.querySelector('.slider__btn-next');\n  var sliderLine = document.querySelector('.cottage-slider__items');\n  var offset = 0;\n  console.log(sliderLine);\n  nextBtn.addEventListener('click', function () {\n    offset += 1230;\n    if (offset > 6150) {\n      offset = 0;\n    }\n    sliderLine.style.left = \"\".concat(-offset, \"px\");\n  });\n  prevBtn.addEventListener('click', function () {\n    offset -= 1230;\n    if (offset < 0) {\n      offset = 6150;\n    }\n    sliderLine.style.left = \"\".concat(-offset, \"px\");\n  });\n};\n\n//# sourceURL=webpack://start/./src/js/cottage-slider.js?")},"./src/js/main-slider.js":
/*!*******************************!*\
  !*** ./src/js/main-slider.js ***!
  \*******************************/(__unused_webpack_module,__webpack_exports__,__webpack_require__)=>{eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export */ __webpack_require__.d(__webpack_exports__, {\n/* harmony export */   \"mainSlider\": () => (/* binding */ mainSlider)\n/* harmony export */ });\nvar mainSlider = function mainSlider() {\n  var btnPrev = document.querySelector('.slider__btn-prev');\n  var btnNext = document.querySelector('.slider__btn-next');\n  var slidersLine = document.querySelector('.slider__line');\n  var offset = 0;\n  btnNext.addEventListener('click', function () {\n    offset += 1920;\n    if (offset > 3840) {\n      offset = 0;\n    }\n    ;\n    slidersLine.style.left = \"\".concat(-offset, \"px\");\n  });\n  btnPrev.addEventListener('click', function () {\n    offset -= 1920;\n    if (offset < 0) {\n      offset = 3840;\n    }\n    ;\n    slidersLine.style.left = \"\".concat(-offset, \"px\");\n  });\n};\n\n//# sourceURL=webpack://start/./src/js/main-slider.js?")},"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/(__unused_webpack_module,__webpack_exports__,__webpack_require__)=>{eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _app__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./app */ "./src/js/app.js");\n/* harmony import */ var _cottage_slider__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./cottage-slider */ "./src/js/cottage-slider.js");\n/* harmony import */ var _main_slider__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./main-slider */ "./src/js/main-slider.js");\n\n\n\n(0,_app__WEBPACK_IMPORTED_MODULE_0__.offerAccordions)();\n(0,_cottage_slider__WEBPACK_IMPORTED_MODULE_1__.gallarySlider)();\n(0,_main_slider__WEBPACK_IMPORTED_MODULE_2__.mainSlider)();\n\n//# sourceURL=webpack://start/./src/js/main.js?')}},__webpack_module_cache__={};function __webpack_require__(e){var r=__webpack_module_cache__[e];if(void 0!==r)return r.exports;var n=__webpack_module_cache__[e]={exports:{}};return __webpack_modules__[e](n,n.exports,__webpack_require__),n.exports}__webpack_require__.d=(e,r)=>{for(var n in r)__webpack_require__.o(r,n)&&!__webpack_require__.o(e,n)&&Object.defineProperty(e,n,{enumerable:!0,get:r[n]})},__webpack_require__.o=(e,r)=>Object.prototype.hasOwnProperty.call(e,r),__webpack_require__.r=e=>{"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})};var __webpack_exports__=__webpack_require__("./src/js/main.js")})();
//# sourceMappingURL=main.js.map
